export enum Resource {
  DASHBOARD = 'dashboard',
  STOCK = 'stock',
  ORDERS = 'orders',
  CLIENTS = 'clients',
  SUPPLIERS = 'suppliers',
  STOCK_MOVEMENTS = 'stockMovements',
  PRODUCTS = 'products',
  LOCATIONS = 'locations',
  INVENTORY = 'inventory',
  AUDIT_LOGS = 'auditLogs',
  USERS = 'users',
  SETTINGS = 'settings',
  ROLES = 'roles',
}
